minimum_cumulusci_version: '3.74.0'
project:
    name: FSC-Actionable-Segmentation
    package:
        name: FSC-Actionable-Segmentation
        api_version: '58.0'
    git:
        default_branch: 'main'
        prefix_feature: 'feature/'
        prefix_beta: 'beta/'
        prefix_release: 'release/'
    source_format: sfdx

tasks:
    robot:
        options:
            suites: robot/FSC-Actionable-Segmentation/tests
            options:
                outputdir: robot/FSC-Actionable-Segmentation/results

    robot_testdoc:
        options:
            path: robot/FSC-Actionable-Segmentation/tests
            output: robot/FSC-Actionable-Segmentation/doc/FSC-Actionable-Segmentation_tests.html

    run_tests:
        options:
            required_org_code_coverage_percent: 75

    install_crma_app:
        description: Anonymous apex code execution before installation
        class_path: cumulusci.tasks.apex.anon.AnonymousApexTask
        options:
            apex: |
                try {
                    Map<String, Object> configuration = new Map<String, Object>();
                    Map<String, Object> appConfiguration = new Map<String,Object>();
                    appConfiguration.put('deleteAppOnConstructionFailure', true);
                    configuration.put('appConfiguration', appConfiguration);
                    WaveAutoInstallRequest newRequest = new WaveAutoInstallRequest();
                    newRequest.put('Name', 'Test WaveAppCreate request');
                    newRequest.put('TemplateApiName', 'sfdc_internal__ActionableSegmentation');
                    newRequest.put('RequestStatus', 'Enqueued');
                    newRequest.put('RequestType', 'WaveAppCreate');
                    newRequest.put('Configuration', JSON.serialize(configuration));
                    System.debug('Installig CRMA app...');
                    insert newRequest;
                } catch(Exception e) {
                    System.debug('There is an exception while installing CRMA app' + e);
                }

    create_interest_tags:
        description: Creates interest tags using connect API
        class_path: cumulusci_ext.tasks.industries.create_interest_tags.CreateInterestTags

flows:
    dependencies:
        steps:
            3:
                task: install_crma_app
            4:
                task: util_sleep
                options:
                    seconds: 60

    config_dev:
        steps:
            3:
                task: generate_and_load_from_yaml
                options:
                    generator_yaml: recipe_tag_category.yml
            4:
                task: create_interest_tags
                options:
                    tags_per_category: 3
            5:
                task: generate_and_load_from_yaml
                options:
                    generator_yaml: recipe_account.yml
                    num_records: 100
                    num_records_tablename: Account
                    batch_size: 1

    fsc_actionable_segmentation_install:
        steps:
            1:
                task: install_crma_app
                ui_options:
                    name: Install CRMA application to enable Actionable Segmentation
            2:
                task: util_sleep
                options:
                    seconds: 60
                ui_options:
                    name: Wait until CRMA application is installed
            3:
                task: deploy
                options:
                    path: force-app/main/default/
                ui_options:
                    name: Deploy metadata

    fsc_actionable_segmentation_load_data:
        steps:
            1:
                task: generate_and_load_from_yaml
                options:
                    generator_yaml: recipe_tag_category.yml
                ui_options:
                    name: Create tag categories
            2:
                task: create_interest_tags
                options:
                    tags_per_category: 3
                ui_options:
                    name: Create Interest Tags
            3:
                task: generate_and_load_from_yaml
                options:
                    generator_yaml: recipe_account.yml
                    num_records: 100
                    num_records_tablename: Account
                    batch_size: 1
                ui_options:
                    name: Load Account, Financial Account, and Assets and Liabilities

    fsc_actionable_segmentation:
        steps:
            1:
                flow: fsc_actionable_segmentation_install
            2:
                flow: fsc_actionable_segmentation_load_data

plans:
    install:
        slug: install
        title: FSC Actionable Segmentation
        tier: primary
        is_listed: True
        preflight_message: "This will install FSC Actionable Segmentation feature"
        post_install_message: "Thank you for installing FSC Actionable Segmentation Module. "
        error_message: "To get help with this error, go to [help.salesforce.com](https://help.salesforce.com/), find the Support & Services area and log a technical support ticket with Salesforce. Include “PMM” in the subject line and include in your comment the installation link shown here."
        checks:
            - when: "'SonicEmbeddedStorePsl' not in tasks.get_available_permission_set_licenses()"
              action: error
              message: "You need SonicEmbeddedStorePsl licence to use this feature. Contact your Administrator."
            - when: "'DataPipelinesAddOnPsl' not in tasks.get_available_permission_set_licenses()"
              action: error
              message: "You need DataPipelinesAddOnPsl licence to use this feature. Contact your Administrator."
            - when: "'IndustriesServiceExcellencePsl' not in tasks.get_available_permission_set_licenses()"
              action: error
              message: "You need IndustriesServiceExcellencePsl licence to use this feature. Contact your Administrator."
        steps:
            1:
                flow: fsc_actionable_segmentation_install

    install_data:
        slug: install_data
        title: Sample Data Plan
        tier: additional
        is_listed: True
        preflight_message: "This will load data for FSC Actionable Segmentation feature"
        post_install_message: "Thank you for installing FSC Actionable Segmentation Module and loading data. "
        error_message: "To get help with this error, go to [help.salesforce.com](https://help.salesforce.com/), find the Support & Services area and log a technical support ticket with Salesforce. Include “PMM” in the subject line and include in your comment the installation link shown here."
        checks:
            - when: "'SonicEmbeddedStorePsl' not in tasks.get_available_permission_set_licenses()"
              action: error
              message: "You need SonicEmbeddedStorePsl licence to use this feature. Contact your Administrator."
            - when: "'DataPipelinesAddOnPsl' not in tasks.get_available_permission_set_licenses()"
              action: error
              message: "You need DataPipelinesAddOnPsl licence to use this feature. Contact your Administrator."
            - when: "'IndustriesServiceExcellencePsl' not in tasks.get_available_permission_set_licenses()"
              action: error
              message: "You need IndustriesServiceExcellencePsl licence to use this feature. Contact your Administrator."
        steps:
            1:
                flow: fsc_actionable_segmentation_load_data
